---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos_7
    image: centos7_testroles:latest
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        vector_host_ip: localhost
        clickhouse_host_ip: localhost
        lighthouse_host_ip: localhost
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy
