# handlers file for vector_role
---
- name: start-vector-systemd
  become: true
  ansible.builtin.systemd:
    name: vector
    state: started
    daemon_reload: true
  when:
    - not ansible_check_mode
    - ansible_virtualization_type != "docker"
    - ansible_virtualization_type != "kvm"
