---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        clickhouse_host_ip: localhost
verifier:
  name: ansible
#scenario:
#  test_sequence:
#    - cleanup
#    - destroy
#    - lint
lint: |
  ansible-lint .
  yamllint .